#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# 一个打印函数，前后加空行
function print(){
    echo "===========$*============"
}

print 提高修养

wd=`pwd`
rm -f temp

is_err=0

re=`./gradlew checkstyleMain >> temp`
err=`cat temp | grep "ERROR"`
if [ $err = *"ERROR"* ];then
    print $err
    is_err=1
fi

print "检查完成"

rm -f temp

if [ $is_err -ne 0 ];
then
    print "请先符合style才能提交！"
    exit 1
fi

exit 0
